### ISSUE TITLE
How is this more flexible?

### ISSUE THREAD

**Issue by tleunen** [Soreine/draft-js-simpledecorator#1]
Hey @Soreine,

I'd like to know how this is more flexible than just having an object with a `strategy` and a `component` property to define a simple decorator.

Maybe you could explain what you solve with this simple decorator? Not sure to understand the need of `getDecorations` and all others draftjs specific functions.

Thanks.

**Comment by Soreine** [comment]
Hi @tleunen,

`SimpleDecorator` asks a `strategy` and a `component`, just like [`Draft.CompositeDecorator`](https://facebook.github.io/draft-js/docs/advanced-topics-decorators.html#compositedecorator) does. The single difference is that it **allows to pass custom props to the decorating Component when applying the strategy**. I found that it was a missing feature in the `CompositeDecorator` interface. 

For example, let's say you want to color any Hex color codes in your text with the color it represent. Here's how you would make a decorator for that, using this module:

``` jsx
const decorator = new SimpleDecorator(

    function strategy(contentBlock, callback) {
        const text = contentBlock.getText()

        // Match examples: #ac00ff #eee ...
        let HEX_COLOR = /#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})/g

        // For all Hex color matches
        let match
        while ((match = HEX_COLOR.exec(text)) !== null) {
            // Decorate the color code
            let colorText = match[0]
            let start = match.index
            let end = start + colorText.length
            let props = {
                color: colorText
            }
            callback(start, end, props)
        }
    },

    /**
     * @prop {String} color
     */
    function component(props) {
        // Colorize the text with the given color
        return <span style={{ color: props.color }}>{ props.children }</span>
    }
)
```

I don't know a way to do that simply with `CompositeDecorator`, because the `component` you give never receives any special props, so it would always render the same. So you are left to implement the [`DecoratorType` interface](https://github.com/facebook/draft-js/blob/master/src/model/decorators/DraftDecoratorType.js) yourself. Here comes `SimpleDecorator` to implements this interface for you.

**Comment by tleunen** [comment]
gotcha, thanks for the explanation :)

**Comment by Soreine** [comment]
Thank you for asking. I'll develop the README.
